[package]
name = "serveur"
version = "0.1.0"
edition = "2021"
authors = ["Mathis THOUVENIN <thouvenin.mathis@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.45"